version: 2

buildSteps: &buildSteps
  - checkout
  - run:
      name: Install
      command: npm install --loglevel warn
  - run:
      name: Test
      command: npm test --loglevel warn

jobs:
  node-6:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-6
    steps: *buildSteps

  node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/node-8
    steps: *buildSteps

  node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/node-10
    steps: *buildSteps

  node-12:
    docker:
      - image: circleci/node:12
    working_directory: ~/node-12
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - node-6
      - node-8
      - node-10
      - node-12
